package VtysProje.views;

import VtysProje.dao.CityDao;
import VtysProje.model.City;
import VtysProje.util.DataModelsInitializer;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by 12043 on 8.12.2017 part of project vtysProje
 */
public class CitiesView extends javax.swing.JPanel {

    private CityDao cityDao = new CityDao();

    private List<City> cities = new ArrayList<>();

    private void refreshCities() {
        cities = cityDao.getAll();
        jTable_cities_list.setModel(DataModelsInitializer.initCitiesTableModel(cities));
    }

    /**
     * Creates new form CitiesView
     */
    public CitiesView() {
        initComponents();
        refreshCities();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_cities = new javax.swing.JPanel();
        jTabbedPane_cities = new javax.swing.JTabbedPane();
        jPanel_cities_add = new javax.swing.JPanel();
        jTextField_cities_add_name = new javax.swing.JTextField();
        jLabel_cities_add_name = new javax.swing.JLabel();
        jLabel_cities_add_code = new javax.swing.JLabel();
        jButton_cities_add = new javax.swing.JButton();
        jComboBox_cities_add_country = new javax.swing.JComboBox<>();
        jLabel_cities_add_country = new javax.swing.JLabel();
        jSpinner_cities_add_code = new javax.swing.JSpinner();
        jPanel_cities_list = new javax.swing.JPanel();
        jScrollPane_cities_list = new javax.swing.JScrollPane();
        jTable_cities_list = new javax.swing.JTable();

        jLabel_cities_add_name.setText("City name:");

        jLabel_cities_add_code.setText("City code:");

        jButton_cities_add.setText("Add");

        jComboBox_cities_add_country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Turkey", "Iraq", "US", "England"}));

        jLabel_cities_add_country.setText("Country:");

        javax.swing.GroupLayout jPanel_cities_addLayout = new javax.swing.GroupLayout(jPanel_cities_add);
        jPanel_cities_add.setLayout(jPanel_cities_addLayout);
        jPanel_cities_addLayout.setHorizontalGroup(
                jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_cities_addLayout.createSequentialGroup()
                                .addGroup(jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel_cities_addLayout.createSequentialGroup()
                                                .addGap(260, 260, 260)
                                                .addGroup(jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel_cities_add_name)
                                                        .addComponent(jLabel_cities_add_code)
                                                        .addComponent(jLabel_cities_add_country))
                                                .addGap(39, 39, 39)
                                                .addGroup(jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSpinner_cities_add_code, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                                        .addComponent(jTextField_cities_add_name, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                                        .addComponent(jComboBox_cities_add_country, 0, 82, Short.MAX_VALUE)))
                                        .addGroup(jPanel_cities_addLayout.createSequentialGroup()
                                                .addGap(294, 294, 294)
                                                .addComponent(jButton_cities_add, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(288, 288, 288))
        );
        jPanel_cities_addLayout.setVerticalGroup(
                jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_cities_addLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField_cities_add_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_cities_add_name))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_cities_add_code)
                                        .addComponent(jSpinner_cities_add_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox_cities_add_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_cities_add_country))
                                .addGap(18, 18, 18)
                                .addComponent(jButton_cities_add)
                                .addContainerGap(186, Short.MAX_VALUE))
        );

        jTabbedPane_cities.addTab("Add", jPanel_cities_add);

        jTable_cities_list.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null}
                },
                new String[]{
                    "Id", "Name", "Code", "Country"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable_cities_list.setColumnSelectionAllowed(true);
        jScrollPane_cities_list.setViewportView(jTable_cities_list);

        javax.swing.GroupLayout jPanel_cities_listLayout = new javax.swing.GroupLayout(jPanel_cities_list);
        jPanel_cities_list.setLayout(jPanel_cities_listLayout);
        jPanel_cities_listLayout.setHorizontalGroup(
                jPanel_cities_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_cities_listLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_cities_list, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel_cities_listLayout.setVerticalGroup(
                jPanel_cities_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_cities_listLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_cities_list, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane_cities.addTab("List", jPanel_cities_list);
        jPanel_cities_list.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel_citiesLayout = new javax.swing.GroupLayout(jPanel_cities);
        jPanel_cities.setLayout(jPanel_citiesLayout);
        jPanel_citiesLayout.setHorizontalGroup(
                jPanel_citiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane_cities)
        );
        jPanel_citiesLayout.setVerticalGroup(
                jPanel_citiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane_cities)
        );

        jTabbedPane_cities.getAccessibleContext().setAccessibleName("Cites");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 733, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel_cities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 427, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel_cities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cities_add;
    private javax.swing.JComboBox<String> jComboBox_cities_add_country;
    private javax.swing.JLabel jLabel_cities_add_code;
    private javax.swing.JLabel jLabel_cities_add_country;
    private javax.swing.JLabel jLabel_cities_add_name;
    private javax.swing.JPanel jPanel_cities;
    private javax.swing.JPanel jPanel_cities_add;
    private javax.swing.JPanel jPanel_cities_list;
    private javax.swing.JScrollPane jScrollPane_cities_list;
    private javax.swing.JSpinner jSpinner_cities_add_code;
    private javax.swing.JTabbedPane jTabbedPane_cities;
    private javax.swing.JTable jTable_cities_list;
    private javax.swing.JTextField jTextField_cities_add_name;
    // End of variables declaration//GEN-END:variables
}
