/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VtysProje.views;

/**
 *
 * @author 12043
 */
public class ProductsInStockView extends javax.swing.JPanel {

    /**
     * Creates new form productsInStockView
     */
    public ProductsInStockView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_productsInStock = new javax.swing.JPanel();
        jTabbedPane_productsInStock = new javax.swing.JTabbedPane();
        jPanel_productsInStock_add = new javax.swing.JPanel();
        jButton_productsInStock_add = new javax.swing.JButton();
        jLabel_productsInStock_add_stock = new javax.swing.JLabel();
        jComboBox_productsInStock_add_stock = new javax.swing.JComboBox<>();
        jLabel_productsInStock_add_serial = new javax.swing.JLabel();
        jTextField_productsInStock_add_serial = new javax.swing.JTextField();
        jLabel_productsInStocks_add_info1 = new javax.swing.JLabel();
        jCheckBox_productsInStocks_add_defectiveStatus = new javax.swing.JCheckBox();
        jPanel_productsInStock_list = new javax.swing.JPanel();
        jScrollPane_productsInStock_list = new javax.swing.JScrollPane();
        jTable_productsInStock_list = new javax.swing.JTable();
        jComboBox_productsInStocks_list = new javax.swing.JComboBox<>();

        jButton_productsInStock_add.setText("Add");

        jLabel_productsInStock_add_stock.setText("Stock:");

        jComboBox_productsInStock_add_stock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Stock 1", "Stock 2", "Stock 3", "Stock 4"}));

        jLabel_productsInStock_add_serial.setText("Serial:");

        jLabel_productsInStocks_add_info1.setText("(Will be auto generated if empty)");

        jCheckBox_productsInStocks_add_defectiveStatus.setText("Defective");

        javax.swing.GroupLayout jPanel_productsInStock_addLayout = new javax.swing.GroupLayout(jPanel_productsInStock_add);
        jPanel_productsInStock_add.setLayout(jPanel_productsInStock_addLayout);
        jPanel_productsInStock_addLayout.setHorizontalGroup(
                jPanel_productsInStock_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_productsInStock_addLayout.createSequentialGroup()
                                .addContainerGap(249, Short.MAX_VALUE)
                                .addGroup(jPanel_productsInStock_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox_productsInStocks_add_defectiveStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel_productsInStock_addLayout.createSequentialGroup()
                                                .addGroup(jPanel_productsInStock_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel_productsInStock_add_stock)
                                                        .addComponent(jLabel_productsInStock_add_serial))
                                                .addGap(28, 28, 28)
                                                .addGroup(jPanel_productsInStock_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jComboBox_productsInStock_add_stock, 0, 81, Short.MAX_VALUE)
                                                        .addComponent(jTextField_productsInStock_add_serial, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel_productsInStocks_add_info1)))
                                .addGap(133, 133, 133))
                        .addGroup(jPanel_productsInStock_addLayout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addComponent(jButton_productsInStock_add, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_productsInStock_addLayout.setVerticalGroup(
                jPanel_productsInStock_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_productsInStock_addLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel_productsInStock_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox_productsInStock_add_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_productsInStock_add_stock))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_productsInStock_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField_productsInStock_add_serial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_productsInStocks_add_info1)
                                        .addComponent(jLabel_productsInStock_add_serial))
                                .addGap(16, 16, 16)
                                .addComponent(jCheckBox_productsInStocks_add_defectiveStatus)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_productsInStock_add)
                                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane_productsInStock.addTab("Add", jPanel_productsInStock_add);

        jTable_productsInStock_list.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null}
                },
                new String[]{
                    "Id", "Product Name", "Serial", "Defective Status"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane_productsInStock_list.setViewportView(jTable_productsInStock_list);

        jComboBox_productsInStocks_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Stock 1", "Stock 2", "Stock 3", "Stock 4"}));

        javax.swing.GroupLayout jPanel_productsInStock_listLayout = new javax.swing.GroupLayout(jPanel_productsInStock_list);
        jPanel_productsInStock_list.setLayout(jPanel_productsInStock_listLayout);
        jPanel_productsInStock_listLayout.setHorizontalGroup(
                jPanel_productsInStock_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_productsInStock_listLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel_productsInStock_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane_productsInStock_list, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                                        .addGroup(jPanel_productsInStock_listLayout.createSequentialGroup()
                                                .addComponent(jComboBox_productsInStocks_list, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel_productsInStock_listLayout.setVerticalGroup(
                jPanel_productsInStock_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_productsInStock_listLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jComboBox_productsInStocks_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane_productsInStock_list, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(103, Short.MAX_VALUE))
        );

        jTabbedPane_productsInStock.addTab("List", jPanel_productsInStock_list);

        javax.swing.GroupLayout jPanel_productsInStockLayout = new javax.swing.GroupLayout(jPanel_productsInStock);
        jPanel_productsInStock.setLayout(jPanel_productsInStockLayout);
        jPanel_productsInStockLayout.setHorizontalGroup(
                jPanel_productsInStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane_productsInStock)
        );
        jPanel_productsInStockLayout.setVerticalGroup(
                jPanel_productsInStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane_productsInStock)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 733, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel_productsInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 427, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel_productsInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_productsInStock_add;
    private javax.swing.JCheckBox jCheckBox_productsInStocks_add_defectiveStatus;
    private javax.swing.JComboBox<String> jComboBox_productsInStock_add_stock;
    private javax.swing.JComboBox<String> jComboBox_productsInStocks_list;
    private javax.swing.JLabel jLabel_productsInStock_add_serial;
    private javax.swing.JLabel jLabel_productsInStock_add_stock;
    private javax.swing.JLabel jLabel_productsInStocks_add_info1;
    private javax.swing.JPanel jPanel_productsInStock;
    private javax.swing.JPanel jPanel_productsInStock_add;
    private javax.swing.JPanel jPanel_productsInStock_list;
    private javax.swing.JScrollPane jScrollPane_productsInStock_list;
    private javax.swing.JTabbedPane jTabbedPane_productsInStock;
    private javax.swing.JTable jTable_productsInStock_list;
    private javax.swing.JTextField jTextField_productsInStock_add_serial;
    // End of variables declaration//GEN-END:variables
}
