/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VtysProje.views;

import VtysProje.model.Stock;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author 12043
 */
public class StocksView extends javax.swing.JPanel {

    private List<Stock> stocks = new ArrayList<>();

    /**
     * Creates new form StocksView
     */
    public StocksView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_stocks = new javax.swing.JPanel();
        jTabbedPane_stocks = new javax.swing.JTabbedPane();
        jPanel_stocks_add = new javax.swing.JPanel();
        jLabel_stocks_add_product = new javax.swing.JLabel();
        jButton_stocks_add = new javax.swing.JButton();
        jTextField_stocks_add_unitPrice = new javax.swing.JTextField();
        jLabel_stocks_add_unitPrice = new javax.swing.JLabel();
        jLabel_stocks_add_quantity = new javax.swing.JLabel();
        jTextField_stocks_add_quantity = new javax.swing.JTextField();
        jComboBox_stocks_add_product = new javax.swing.JComboBox<>();
        jTextField_stocks_add_name = new javax.swing.JTextField();
        jLabel_stocks_add_name = new javax.swing.JLabel();
        jPanel_stocks_list = new javax.swing.JPanel();
        jScrollPane_stocks_list = new javax.swing.JScrollPane();
        jTable_stocks_list = new javax.swing.JTable();

        jLabel_stocks_add_product.setText("Product:");

        jButton_stocks_add.setText("Add");

        jTextField_stocks_add_unitPrice.setText("Unit price");

        jLabel_stocks_add_unitPrice.setText("Unit price (In Stock):");

        jLabel_stocks_add_quantity.setText("Quantity:");

        jTextField_stocks_add_quantity.setText("Quantity");

        jComboBox_stocks_add_product.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Product 1", "Product 2", "Product 3", "Product 4"}));

        jTextField_stocks_add_name.setText("Stock name");

        jLabel_stocks_add_name.setText("Stock name:");

        javax.swing.GroupLayout jPanel_stocks_addLayout = new javax.swing.GroupLayout(jPanel_stocks_add);
        jPanel_stocks_add.setLayout(jPanel_stocks_addLayout);
        jPanel_stocks_addLayout.setHorizontalGroup(
                jPanel_stocks_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_stocks_addLayout.createSequentialGroup()
                                .addContainerGap(207, Short.MAX_VALUE)
                                .addGroup(jPanel_stocks_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_stocks_add_unitPrice)
                                        .addComponent(jLabel_stocks_add_product)
                                        .addComponent(jLabel_stocks_add_quantity)
                                        .addComponent(jLabel_stocks_add_name))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_stocks_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel_stocks_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField_stocks_add_unitPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                                .addComponent(jTextField_stocks_add_quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                                .addComponent(jTextField_stocks_add_name, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                                        .addComponent(jComboBox_stocks_add_product, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(308, 308, 308))
                        .addGroup(jPanel_stocks_addLayout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(jButton_stocks_add, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_stocks_addLayout.setVerticalGroup(
                jPanel_stocks_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_stocks_addLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel_stocks_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel_stocks_add_product)
                                        .addComponent(jComboBox_stocks_add_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_stocks_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField_stocks_add_unitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_stocks_add_unitPrice))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_stocks_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField_stocks_add_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_stocks_add_name))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_stocks_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField_stocks_add_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_stocks_add_quantity))
                                .addGap(18, 18, 18)
                                .addComponent(jButton_stocks_add)
                                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane_stocks.addTab("Add", jPanel_stocks_add);

        jTable_stocks_list.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null, null}
                },
                new String[]{
                    "Id", "Product Name", "Unit Price", "Unit Price In Stock", "Quantity", "Detail"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane_stocks_list.setViewportView(jTable_stocks_list);

        javax.swing.GroupLayout jPanel_stocks_listLayout = new javax.swing.GroupLayout(jPanel_stocks_list);
        jPanel_stocks_list.setLayout(jPanel_stocks_listLayout);
        jPanel_stocks_listLayout.setHorizontalGroup(
                jPanel_stocks_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_stocks_listLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_stocks_list, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel_stocks_listLayout.setVerticalGroup(
                jPanel_stocks_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_stocks_listLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_stocks_list, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane_stocks.addTab("List", jPanel_stocks_list);

        javax.swing.GroupLayout jPanel_stocksLayout = new javax.swing.GroupLayout(jPanel_stocks);
        jPanel_stocks.setLayout(jPanel_stocksLayout);
        jPanel_stocksLayout.setHorizontalGroup(
                jPanel_stocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane_stocks)
        );
        jPanel_stocksLayout.setVerticalGroup(
                jPanel_stocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane_stocks)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 733, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel_stocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 427, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel_stocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_stocks_add;
    private javax.swing.JComboBox<String> jComboBox_stocks_add_product;
    private javax.swing.JLabel jLabel_stocks_add_name;
    private javax.swing.JLabel jLabel_stocks_add_product;
    private javax.swing.JLabel jLabel_stocks_add_quantity;
    private javax.swing.JLabel jLabel_stocks_add_unitPrice;
    private javax.swing.JPanel jPanel_stocks;
    private javax.swing.JPanel jPanel_stocks_add;
    private javax.swing.JPanel jPanel_stocks_list;
    private javax.swing.JScrollPane jScrollPane_stocks_list;
    private javax.swing.JTabbedPane jTabbedPane_stocks;
    private javax.swing.JTable jTable_stocks_list;
    private javax.swing.JTextField jTextField_stocks_add_name;
    private javax.swing.JTextField jTextField_stocks_add_quantity;
    private javax.swing.JTextField jTextField_stocks_add_unitPrice;
    // End of variables declaration//GEN-END:variables
}
