package VtysProje.views;

import VtysProje.model.User;
import VtysProje.util.DataCache;
import VtysProje.util.DataModelsInitializer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * Created by 12043 on 8.12.2017 part of project vtysProje
 */
public class UsersView extends javax.swing.JPanel {

    private void refreshUsers() {
        DataCache.refreshRoles();
        DataCache.refreshUsers();
        DefaultComboBoxModel<String> rolesModel = DataModelsInitializer.initRolesComboBoxModel(DataCache.roles);
        jComboBox_users_add_role.setModel(rolesModel);
        jComboBox_users_edit_role.setModel(rolesModel);

        DefaultComboBoxModel<String> citiesModel = DataModelsInitializer.initCitiesComboBoxModel(DataCache.cities);
        jComboBox_users_add_city.setModel(citiesModel);
        jComboBox_users_edit_city.setModel(citiesModel);

        jComboBox_users_edit_select.setModel(DataModelsInitializer.initUsersComboBoxModel(DataCache.users));
        jTable_users_list.setModel(DataModelsInitializer.initUsersTableModel(DataCache.users));
    }

    /**
     * Creates new form UsersView
     */
    public UsersView() {
        initComponents();
        refreshUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_users = new javax.swing.JPanel();
        jTabbedPane_users = new javax.swing.JTabbedPane();
        jPanel_users_add = new javax.swing.JPanel();
        jTextField_users_add_username = new javax.swing.JTextField();
        jLabel_users_add_username = new javax.swing.JLabel();
        jLabel_users_add_firstName = new javax.swing.JLabel();
        jTextField_users_add_firstName = new javax.swing.JTextField();
        jButton_users_add = new javax.swing.JButton();
        jComboBox_users_add_city = new javax.swing.JComboBox<>();
        jLabel_users_add_city = new javax.swing.JLabel();
        jTextField_users_add_lastName = new javax.swing.JTextField();
        jLabel_users_add_lastName = new javax.swing.JLabel();
        jLabel_users_add_password = new javax.swing.JLabel();
        jTextField_users_add_password = new javax.swing.JTextField();
        jScrollPane_users_add_address = new javax.swing.JScrollPane();
        jTextArea_users_add_address = new javax.swing.JTextArea();
        jLabel_users_add_address = new javax.swing.JLabel();
        jLabel_users_add_phoneNumber = new javax.swing.JLabel();
        jTextField_users_add_phoneNumber = new javax.swing.JTextField();
        jComboBox_users_add_role = new javax.swing.JComboBox<>();
        jLabel_users_add_role = new javax.swing.JLabel();
        jLabel_users_add_birthDay = new javax.swing.JLabel();
        jTextField_users_add_birthDay = new javax.swing.JTextField();
        jPanel_users_list = new javax.swing.JPanel();
        jScrollPane_users_list = new javax.swing.JScrollPane();
        jTable_users_list = new javax.swing.JTable();
        jButton_users_list_delete = new javax.swing.JButton();
        jPanel_users_edit = new javax.swing.JPanel();
        jTextField_users_edit_username = new javax.swing.JTextField();
        jLabel_users_edit_username = new javax.swing.JLabel();
        jLabel_users_edit_firstName = new javax.swing.JLabel();
        jTextField_users_edit_firstName = new javax.swing.JTextField();
        jButton_users_edit = new javax.swing.JButton();
        jComboBox_users_edit_city = new javax.swing.JComboBox<>();
        jLabel_users_edit_city = new javax.swing.JLabel();
        jTextField_users_edit_lastName = new javax.swing.JTextField();
        jLabel_users_edit_lastName = new javax.swing.JLabel();
        jLabel_users_edit_password = new javax.swing.JLabel();
        jTextField_users_edit_password = new javax.swing.JTextField();
        jScrollPane_users_edit_address = new javax.swing.JScrollPane();
        jTextArea_users_edit_address = new javax.swing.JTextArea();
        jLabel_users_edit_address = new javax.swing.JLabel();
        jLabel_users_edit_phoneNumber = new javax.swing.JLabel();
        jTextField_users_edit_phoneNumber = new javax.swing.JTextField();
        jComboBox_users_edit_select = new javax.swing.JComboBox<>();
        jLabel_users_edit_select = new javax.swing.JLabel();
        jComboBox_users_edit_role = new javax.swing.JComboBox<>();
        jLabel_users_edit_role1 = new javax.swing.JLabel();
        jLabel_users_edit_birthDay = new javax.swing.JLabel();
        jTextField_users_edit_birthDay = new javax.swing.JTextField();

        jLabel_users_add_username.setText("Username:");

        jLabel_users_add_firstName.setText("First name:");

        jButton_users_add.setText("Add");
        jButton_users_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_users_addActionPerformed(evt);
            }
        });

        jComboBox_users_add_city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ankara", "London", "New York", "Fizan" }));

        jLabel_users_add_city.setText("City:");

        jLabel_users_add_lastName.setText("Last name:");

        jLabel_users_add_password.setText("Password:");

        jTextArea_users_add_address.setColumns(20);
        jTextArea_users_add_address.setRows(5);
        jScrollPane_users_add_address.setViewportView(jTextArea_users_add_address);

        jLabel_users_add_address.setText("Address:");

        jLabel_users_add_phoneNumber.setText("Phone number:");

        jComboBox_users_add_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Customer" }));

        jLabel_users_add_role.setText("Role:");

        jLabel_users_add_birthDay.setText("Birthday:");

        javax.swing.GroupLayout jPanel_users_addLayout = new javax.swing.GroupLayout(jPanel_users_add);
        jPanel_users_add.setLayout(jPanel_users_addLayout);
        jPanel_users_addLayout.setHorizontalGroup(
            jPanel_users_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_users_addLayout.createSequentialGroup()
                .addGroup(jPanel_users_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_users_addLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(jPanel_users_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_users_add_username)
                            .addComponent(jLabel_users_add_firstName)
                            .addComponent(jLabel_users_add_lastName)
                            .addComponent(jLabel_users_add_password)
                            .addComponent(jLabel_users_add_address)
                            .addComponent(jLabel_users_add_phoneNumber)
                            .addComponent(jLabel_users_add_city)
                            .addComponent(jLabel_users_add_role)
                            .addComponent(jLabel_users_add_birthDay))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel_users_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_users_add_city, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_users_add_username, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_users_add_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_users_add_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_users_add_password, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane_users_add_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_users_add_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_users_add_role, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_users_add_birthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_users_addLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jButton_users_add, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel_users_addLayout.setVerticalGroup(
            jPanel_users_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_users_addLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_users_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_users_add_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_add_role))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_users_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_users_add_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_add_username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_users_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_users_add_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_add_firstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_users_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_users_add_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_add_lastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_users_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_users_add_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_add_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_users_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_users_add_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_add_phoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_users_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_users_add_birthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_add_birthDay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_users_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_users_add_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_add_city))
                .addGap(18, 18, 18)
                .addGroup(jPanel_users_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_users_add_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_add_address))
                .addGap(18, 18, 18)
                .addComponent(jButton_users_add)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane_users.addTab("Add", jPanel_users_add);

        jTable_users_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "City", "Username", "First name", "Last name", "Password", "Address", "Phone Number", "Role", "Birthday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_users_list.setColumnSelectionAllowed(true);
        jScrollPane_users_list.setViewportView(jTable_users_list);
        jTable_users_list.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jButton_users_list_delete.setText("Delete");
        jButton_users_list_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_users_list_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_users_listLayout = new javax.swing.GroupLayout(jPanel_users_list);
        jPanel_users_list.setLayout(jPanel_users_listLayout);
        jPanel_users_listLayout.setHorizontalGroup(
            jPanel_users_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_users_listLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_users_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_users_list, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addGroup(jPanel_users_listLayout.createSequentialGroup()
                        .addComponent(jButton_users_list_delete)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_users_listLayout.setVerticalGroup(
            jPanel_users_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_users_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_users_list, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton_users_list_delete)
                .addContainerGap())
        );

        jTabbedPane_users.addTab("List", jPanel_users_list);

        jLabel_users_edit_username.setText("Username:");

        jLabel_users_edit_firstName.setText("First name:");

        jButton_users_edit.setText("Save");
        jButton_users_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_users_editActionPerformed(evt);
            }
        });

        jComboBox_users_edit_city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ankara", "London", "New York", "Fizan" }));

        jLabel_users_edit_city.setText("City:");

        jLabel_users_edit_lastName.setText("Last name:");

        jLabel_users_edit_password.setText("Password:");

        jTextArea_users_edit_address.setColumns(20);
        jTextArea_users_edit_address.setRows(5);
        jScrollPane_users_edit_address.setViewportView(jTextArea_users_edit_address);

        jLabel_users_edit_address.setText("Address:");

        jLabel_users_edit_phoneNumber.setText("Phone number:");

        jComboBox_users_edit_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User 1", "User 2", "User 3" }));
        jComboBox_users_edit_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_users_edit_selectActionPerformed(evt);
            }
        });

        jLabel_users_edit_select.setText("Editing User:");

        jComboBox_users_edit_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Customer" }));

        jLabel_users_edit_role1.setText("Role:");

        jLabel_users_edit_birthDay.setText("Birthday:");

        javax.swing.GroupLayout jPanel_users_editLayout = new javax.swing.GroupLayout(jPanel_users_edit);
        jPanel_users_edit.setLayout(jPanel_users_editLayout);
        jPanel_users_editLayout.setHorizontalGroup(
            jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_users_editLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_users_editLayout.createSequentialGroup()
                        .addGroup(jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_users_edit_username)
                            .addComponent(jLabel_users_edit_firstName)
                            .addComponent(jLabel_users_edit_lastName)
                            .addComponent(jLabel_users_edit_password)
                            .addComponent(jLabel_users_edit_address)
                            .addComponent(jLabel_users_edit_phoneNumber)
                            .addComponent(jLabel_users_edit_city)
                            .addComponent(jLabel_users_edit_select)
                            .addComponent(jLabel_users_edit_role1)
                            .addComponent(jLabel_users_edit_birthDay))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_users_edit_city, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_users_edit_username, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_users_edit_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_users_edit_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_users_edit_password, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane_users_edit_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_users_edit_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_users_edit_select, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_users_edit_role, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_users_edit_birthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_users_editLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton_users_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel_users_editLayout.setVerticalGroup(
            jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_users_editLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_users_edit_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_edit_select))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_users_edit_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_edit_role1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_users_edit_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_edit_username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_users_edit_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_edit_firstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_users_edit_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_edit_lastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_users_edit_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_edit_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_users_edit_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_edit_phoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_users_edit_birthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_edit_birthDay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_users_edit_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_edit_city))
                .addGap(18, 18, 18)
                .addGroup(jPanel_users_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_users_edit_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_users_edit_address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_users_edit)
                .addGap(24, 24, 24))
        );

        jTabbedPane_users.addTab("Edit", jPanel_users_edit);

        javax.swing.GroupLayout jPanel_usersLayout = new javax.swing.GroupLayout(jPanel_users);
        jPanel_users.setLayout(jPanel_usersLayout);
        jPanel_usersLayout.setHorizontalGroup(
            jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_users)
        );
        jPanel_usersLayout.setVerticalGroup(
            jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_users)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_users_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_users_addActionPerformed
        User user = new User();
        user.setFirstName(jTextField_users_add_firstName.getText());
        user.setLastName(jTextField_users_add_lastName.getText());
        user.setUserName(jTextField_users_add_username.getText());
        user.setPassword(jTextField_users_add_password.getText());
        user.setAddress(jTextArea_users_add_address.getText());
        user.setPhoneNumber(jTextField_users_add_phoneNumber.getText());
        user.setRoleId(DataCache.roles.get(jComboBox_users_add_role.getSelectedIndex() - 1).getId());
        user.setCityId(DataCache.cities.get(jComboBox_users_add_city.getSelectedIndex() - 1).getId());
        user.setBirthDay(jTextField_users_add_birthDay.getText());

        if (DataCache.userDao.add(user)) {
            JOptionPane.showMessageDialog(this, "Added successfully");
            jTextField_users_add_firstName.setText("");
            jTextField_users_add_lastName.setText("");
            jTextField_users_add_username.setText("");
            jTextField_users_add_password.setText("");
            jTextArea_users_add_address.setText("");
            jTextField_users_add_phoneNumber.setText("");
            jTextField_users_add_birthDay.setText("");
            refreshUsers();
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_jButton_users_addActionPerformed

    private void jButton_users_list_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_users_list_deleteActionPerformed
        int selectedIndex = jTable_users_list.getSelectedRow();
        if (DataCache.userDao.delete((int) jTable_users_list.getValueAt(selectedIndex, 0))) {
            JOptionPane.showMessageDialog(this, "Deleted successfully");
            refreshUsers();
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_jButton_users_list_deleteActionPerformed

    private void jButton_users_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_users_editActionPerformed
        User user = new User();
        user.setFirstName(jTextField_users_edit_firstName.getText());
        user.setLastName(jTextField_users_edit_lastName.getText());
        user.setUserName(jTextField_users_edit_username.getText());
        user.setPassword(jTextField_users_edit_password.getText());
        user.setAddress(jTextArea_users_edit_address.getText());
        user.setPhoneNumber(jTextField_users_edit_phoneNumber.getText());
        user.setRoleId(DataCache.roles.get(jComboBox_users_edit_role.getSelectedIndex() - 1).getId());
        user.setCityId(DataCache.cities.get(jComboBox_users_edit_city.getSelectedIndex() - 1).getId());
        user.setId(DataCache.users.get(jComboBox_users_edit_select.getSelectedIndex() - 1).getId());
        user.setBirthDay(jTextField_users_edit_birthDay.getText());

        if (DataCache.userDao.update(user)) {
            JOptionPane.showMessageDialog(this, "Updated successfully");
            jTextField_users_edit_firstName.setText("");
            jTextField_users_edit_lastName.setText("");
            jTextField_users_edit_username.setText("");
            jTextField_users_edit_password.setText("");
            jTextArea_users_edit_address.setText("");
            jTextField_users_edit_phoneNumber.setText("");
            jTextField_users_edit_birthDay.setText("");
            refreshUsers();
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_jButton_users_editActionPerformed

    private void jComboBox_users_edit_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_users_edit_selectActionPerformed
        int selectedIndex = jComboBox_users_edit_select.getSelectedIndex();
        if (selectedIndex == 0) {
            jComboBox_users_edit_role.setSelectedIndex(0);
            jTextField_users_edit_firstName.setText("");
            jTextField_users_edit_lastName.setText("");
            jTextField_users_edit_username.setText("");
            jTextField_users_edit_password.setText("");
            jTextArea_users_edit_address.setText("");
            jTextField_users_edit_phoneNumber.setText("");
            jComboBox_users_edit_city.setSelectedIndex(0);
            jTextField_users_edit_birthDay.setText("");
            return;
        }

        User user = DataCache.users.get(selectedIndex - 1);
        jComboBox_users_edit_role.setSelectedItem(user.getRole().getRole_name());
        jTextField_users_edit_firstName.setText(user.getFirstName());
        jTextField_users_edit_lastName.setText(user.getLastName());
        jTextField_users_edit_username.setText(user.getUserName());
        jTextField_users_edit_password.setText(user.getPassword());
        jTextArea_users_edit_address.setText(user.getAddress());
        jTextField_users_edit_phoneNumber.setText(user.getPhoneNumber());
        jComboBox_users_edit_city.setSelectedItem(user.getCity().getName());
        jTextField_users_edit_birthDay.setText(user.getBirthDay());
    }//GEN-LAST:event_jComboBox_users_edit_selectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_users_add;
    private javax.swing.JButton jButton_users_edit;
    private javax.swing.JButton jButton_users_list_delete;
    private javax.swing.JComboBox<String> jComboBox_users_add_city;
    private javax.swing.JComboBox<String> jComboBox_users_add_role;
    private javax.swing.JComboBox<String> jComboBox_users_edit_city;
    private javax.swing.JComboBox<String> jComboBox_users_edit_role;
    private javax.swing.JComboBox<String> jComboBox_users_edit_select;
    private javax.swing.JLabel jLabel_users_add_address;
    private javax.swing.JLabel jLabel_users_add_birthDay;
    private javax.swing.JLabel jLabel_users_add_city;
    private javax.swing.JLabel jLabel_users_add_firstName;
    private javax.swing.JLabel jLabel_users_add_lastName;
    private javax.swing.JLabel jLabel_users_add_password;
    private javax.swing.JLabel jLabel_users_add_phoneNumber;
    private javax.swing.JLabel jLabel_users_add_role;
    private javax.swing.JLabel jLabel_users_add_username;
    private javax.swing.JLabel jLabel_users_edit_address;
    private javax.swing.JLabel jLabel_users_edit_birthDay;
    private javax.swing.JLabel jLabel_users_edit_city;
    private javax.swing.JLabel jLabel_users_edit_firstName;
    private javax.swing.JLabel jLabel_users_edit_lastName;
    private javax.swing.JLabel jLabel_users_edit_password;
    private javax.swing.JLabel jLabel_users_edit_phoneNumber;
    private javax.swing.JLabel jLabel_users_edit_role1;
    private javax.swing.JLabel jLabel_users_edit_select;
    private javax.swing.JLabel jLabel_users_edit_username;
    private javax.swing.JPanel jPanel_users;
    private javax.swing.JPanel jPanel_users_add;
    private javax.swing.JPanel jPanel_users_edit;
    private javax.swing.JPanel jPanel_users_list;
    private javax.swing.JScrollPane jScrollPane_users_add_address;
    private javax.swing.JScrollPane jScrollPane_users_edit_address;
    private javax.swing.JScrollPane jScrollPane_users_list;
    private javax.swing.JTabbedPane jTabbedPane_users;
    private javax.swing.JTable jTable_users_list;
    private javax.swing.JTextArea jTextArea_users_add_address;
    private javax.swing.JTextArea jTextArea_users_edit_address;
    private javax.swing.JTextField jTextField_users_add_birthDay;
    private javax.swing.JTextField jTextField_users_add_firstName;
    private javax.swing.JTextField jTextField_users_add_lastName;
    private javax.swing.JTextField jTextField_users_add_password;
    private javax.swing.JTextField jTextField_users_add_phoneNumber;
    private javax.swing.JTextField jTextField_users_add_username;
    private javax.swing.JTextField jTextField_users_edit_birthDay;
    private javax.swing.JTextField jTextField_users_edit_firstName;
    private javax.swing.JTextField jTextField_users_edit_lastName;
    private javax.swing.JTextField jTextField_users_edit_password;
    private javax.swing.JTextField jTextField_users_edit_phoneNumber;
    private javax.swing.JTextField jTextField_users_edit_username;
    // End of variables declaration//GEN-END:variables
}
