package VtysProje;

/**
 * Created by 12043 on 8.12.2017
 * part of project vtysProje
 */

// Frame class generated and edited in Netbeans IDE

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_entites = new javax.swing.JTabbedPane();
        jPanel_countries = new javax.swing.JPanel();
        jTabbedPane_countries = new javax.swing.JTabbedPane();
        jPanel_countries_add = new javax.swing.JPanel();
        jTextField_countries_add_name = new javax.swing.JTextField();
        jLabel_countries_add_name = new javax.swing.JLabel();
        jLabel_countries_add_code = new javax.swing.JLabel();
        jTextField_countries_add_code = new javax.swing.JTextField();
        jButton_countries_add = new javax.swing.JButton();
        jPanel_countries_list = new javax.swing.JPanel();
        jScrollPane_countries_list = new javax.swing.JScrollPane();
        jTable_countries = new javax.swing.JTable();
        jPanel_cities = new javax.swing.JPanel();
        jTabbedPane_cities = new javax.swing.JTabbedPane();
        jPanel_cities_add = new javax.swing.JPanel();
        jTextField_cities_add_name = new javax.swing.JTextField();
        jLabel_cities_add_name = new javax.swing.JLabel();
        jLabel_cities_add_code = new javax.swing.JLabel();
        jTextField_cities_add_code = new javax.swing.JTextField();
        jButton_cities_add = new javax.swing.JButton();
        jComboBox_cities_add_country = new javax.swing.JComboBox<>();
        jLabel_cities_add_country = new javax.swing.JLabel();
        jPanel_cities_list = new javax.swing.JPanel();
        jScrollPane_countries_list1 = new javax.swing.JScrollPane();
        jTable_countries1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple CRUD");

        jTextField_countries_add_name.setText("CountryName");

        jLabel_countries_add_name.setText("CountryName:");

        jLabel_countries_add_code.setText("CountryCode:");

        jTextField_countries_add_code.setText("CountryCode");

        jButton_countries_add.setText("Add");

        javax.swing.GroupLayout jPanel_countries_addLayout = new javax.swing.GroupLayout(jPanel_countries_add);
        jPanel_countries_add.setLayout(jPanel_countries_addLayout);
        jPanel_countries_addLayout.setHorizontalGroup(
            jPanel_countries_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_countries_addLayout.createSequentialGroup()
                .addGroup(jPanel_countries_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_countries_addLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jButton_countries_add, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_countries_addLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(jPanel_countries_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_countries_add_code)
                            .addComponent(jLabel_countries_add_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel_countries_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_countries_add_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_countries_add_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(280, 280, 280))
        );
        jPanel_countries_addLayout.setVerticalGroup(
            jPanel_countries_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_countries_addLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel_countries_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_countries_add_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_countries_add_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_countries_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_countries_add_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_countries_add_code))
                .addGap(18, 18, 18)
                .addComponent(jButton_countries_add)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane_countries.addTab("Add", jPanel_countries_add);

        jTable_countries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Id", "Name", "Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_countries.setColumnSelectionAllowed(true);
        jScrollPane_countries_list.setViewportView(jTable_countries);
        jTable_countries.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel_countries_listLayout = new javax.swing.GroupLayout(jPanel_countries_list);
        jPanel_countries_list.setLayout(jPanel_countries_listLayout);
        jPanel_countries_listLayout.setHorizontalGroup(
            jPanel_countries_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_countries_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_countries_list, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_countries_listLayout.setVerticalGroup(
            jPanel_countries_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_countries_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_countries_list, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane_countries.addTab("List", jPanel_countries_list);

        javax.swing.GroupLayout jPanel_countriesLayout = new javax.swing.GroupLayout(jPanel_countries);
        jPanel_countries.setLayout(jPanel_countriesLayout);
        jPanel_countriesLayout.setHorizontalGroup(
            jPanel_countriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_countries)
        );
        jPanel_countriesLayout.setVerticalGroup(
            jPanel_countriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_countries)
        );

        jTabbedPane_countries.getAccessibleContext().setAccessibleName("");

        jTabbedPane_entites.addTab("Countries", jPanel_countries);

        jTextField_cities_add_name.setText("CityName");

        jLabel_cities_add_name.setText("CityName:");

        jLabel_cities_add_code.setText("CityCode:");

        jTextField_cities_add_code.setText("CityCode");

        jButton_cities_add.setText("Add");

        jComboBox_cities_add_country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turkey", "Iraq", "US", "England" }));

        jLabel_cities_add_country.setText("Country:");

        javax.swing.GroupLayout jPanel_cities_addLayout = new javax.swing.GroupLayout(jPanel_cities_add);
        jPanel_cities_add.setLayout(jPanel_cities_addLayout);
        jPanel_cities_addLayout.setHorizontalGroup(
            jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cities_addLayout.createSequentialGroup()
                .addGroup(jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_cities_addLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_cities_add_name)
                            .addComponent(jLabel_cities_add_code)
                            .addComponent(jLabel_cities_add_country))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_cities_add_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_cities_add_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_cities_add_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_cities_addLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jButton_cities_add, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel_cities_addLayout.setVerticalGroup(
            jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cities_addLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_cities_add_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cities_add_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_cities_add_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cities_add_code))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_cities_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_cities_add_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cities_add_country))
                .addGap(18, 18, 18)
                .addComponent(jButton_cities_add)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jTabbedPane_cities.addTab("Add", jPanel_cities_add);

        jTable_countries1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Id", "Country", "Name", "Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane_countries_list1.setViewportView(jTable_countries1);
        jTable_countries1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel_cities_listLayout = new javax.swing.GroupLayout(jPanel_cities_list);
        jPanel_cities_list.setLayout(jPanel_cities_listLayout);
        jPanel_cities_listLayout.setHorizontalGroup(
            jPanel_cities_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cities_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_countries_list1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_cities_listLayout.setVerticalGroup(
            jPanel_cities_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cities_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_countries_list1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane_cities.addTab("List", jPanel_cities_list);

        javax.swing.GroupLayout jPanel_citiesLayout = new javax.swing.GroupLayout(jPanel_cities);
        jPanel_cities.setLayout(jPanel_citiesLayout);
        jPanel_citiesLayout.setHorizontalGroup(
            jPanel_citiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_cities)
        );
        jPanel_citiesLayout.setVerticalGroup(
            jPanel_citiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_cities)
        );

        jTabbedPane_cities.getAccessibleContext().setAccessibleName("");

        jTabbedPane_entites.addTab("Cities", jPanel_cities);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane_entites)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane_entites)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cities_add;
    private javax.swing.JButton jButton_countries_add;
    private javax.swing.JComboBox<String> jComboBox_cities_add_country;
    private javax.swing.JLabel jLabel_cities_add_code;
    private javax.swing.JLabel jLabel_cities_add_country;
    private javax.swing.JLabel jLabel_cities_add_name;
    private javax.swing.JLabel jLabel_countries_add_code;
    private javax.swing.JLabel jLabel_countries_add_name;
    private javax.swing.JPanel jPanel_cities;
    private javax.swing.JPanel jPanel_cities_add;
    private javax.swing.JPanel jPanel_cities_list;
    private javax.swing.JPanel jPanel_countries;
    private javax.swing.JPanel jPanel_countries_add;
    private javax.swing.JPanel jPanel_countries_list;
    private javax.swing.JScrollPane jScrollPane_countries_list;
    private javax.swing.JScrollPane jScrollPane_countries_list1;
    private javax.swing.JTabbedPane jTabbedPane_cities;
    private javax.swing.JTabbedPane jTabbedPane_countries;
    private javax.swing.JTabbedPane jTabbedPane_entites;
    private javax.swing.JTable jTable_countries;
    private javax.swing.JTable jTable_countries1;
    private javax.swing.JTextField jTextField_cities_add_code;
    private javax.swing.JTextField jTextField_cities_add_name;
    private javax.swing.JTextField jTextField_countries_add_code;
    private javax.swing.JTextField jTextField_countries_add_name;
    // End of variables declaration//GEN-END:variables
}
